In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
pip install word2number

  Created wheel for word2number: filename=word2number-1.1-cp36-none-any.whl size=5587 sha256=05b1fb71c21659d5c5029476008264ffe930cd774438b75baec731ab97550b38
  Stored in directory: /root/.cache/pip/wheels/46/2f/53/5f5c1d275492f2fce1cdab9a9bb12d49286dead829a4078e0e
Successfully built word2number


In [3]:
from word2number import w2n

In [9]:
df = pd.read_csv("/content/drive/My Drive/hiring.csv")

In [10]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [11]:
df.test_score

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     NaN
7     7.0
Name: test_score, dtype: float64

In [12]:
df.test_score.median()

8.0

In [17]:
df.test_score = df.test_score.fillna(df.test_score.median())

In [18]:
df

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [19]:
df.experience = df.experience.fillna('zero')

In [20]:
df

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         8.0                7   72000
7     eleven         7.0                8   80000

In [30]:
df.experience = df.experience.apply(w2n.word_to_num)

In [31]:
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [32]:
reg = linear_model.LinearRegression()

In [34]:
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [35]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [38]:
reg.predict([[12,10,10]])

array([92002.18340611])

In [39]:
print(reg.intercept_)
print(reg.coef_)

17737.263464337695
[2812.95487627 1845.70596798 2205.24017467]
