In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv("R:/My Projects/Linear Regression Multivariate/Exercise/hiring.csv")

In [4]:
df


experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [14]:
import math
median_test_score = math.floor(df.test_score.median())
median_test_score

8

In [15]:
df.test_score = df.test_score.fillna(median_test_score)
df

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

In [17]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [20]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [21]:
reg.intercept_

17737.26346433771

In [23]:
reg.predict([[11,7,8]])

array([79241.63027656])

In [24]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [26]:
reg.predict([[12,10,10]])

array([92002.18340611])